echo "//======================="
echo "//01-入场券-generator.cpp"
cat 01-入场券-generator.cpp
echo "//======================="
echo "//02-副本侠-generator.cpp"
cat 02-副本侠-generator.cpp
echo "//======================="
echo "//03-双子牌-generator.cpp"
cat 03-双子牌-generator.cpp 
echo "//======================="
echo "//04-彩虹猫-generator.cpp"
cat 04-彩虹猫-generator.cpp 
echo "//======================="
echo "//05-扮装节-generator.cpp"
cat 05-扮装节-generator.cpp 
echo "//======================="
echo "//06-招聘书-generator.cpp"
cat 06-招聘书-generator.cpp 
echo "//======================="
echo "//07-捏脸师-generator.cpp"
cat 07-捏脸师-generator.cpp 
echo "//======================="
echo "//08-排队论-generator.cpp"
cat 08-排队论-generator.cpp 
echo "//======================="
echo "//09-整向量-generator.cpp"
cat 09-整向量-generator.cpp 
echo "//======================="
echo "//10-欢乐树-generator.cpp"
cat 10-欢乐树-generator.cpp 
echo "//======================="
echo "//11-签到题-generator.cpp"
cat 11-签到题-generator.cpp 
echo "//======================="
echo "//12-金币树-generator.cpp"
cat 12-金币树-generator.cpp 
echo "//======================="
echo "//13-金手帕-generator.cpp"
cat 13-金手帕-generator.cpp 
echo "//======================="
echo "//14-魔法棒-generator.cpp"
cat 14-魔法棒-generator.cpp 
